### ISSUE TITLE
Description too long

### ISSUE THREAD

**Issue by Greenwolf** [asaurusrex/String_Spy#1]
Hi, due to a github update, its not possible to fork this project anymore because your description is over 350 characters. 

Could you please reduce it so I can fork it, add some stuff and issue a pull request?

**Comment by Greenwolf** [comment]
<img width="1321" alt="Screenshot 2022-11-08 at 22 45 11" src="https://user-images.githubusercontent.com/48361984/200595003-2692a2e5-ed05-42a8-8182-a7724582da4e.png">

**Comment by asaurusrex** [comment]
I have shortened the description, please let me know if this is still an issue in the future.
